update

diff --git a/.github/workflows/pr_test.yaml b/.github/workflows/pr_test.yaml
--- a/.github/workflows/pr_test.yaml
+++ b/.github/workflows/pr_test.yaml
@@ -10,17 +10,32 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          submodules: true
 
       - name: Set up Python
         run: |
+          source $(conda info --base)/etc/profile.d/conda.sh
           which python
           echo "Setting up Python with Conda"
           conda create -n test_env python=3.11 -y
-
-      - name: see what python version is
-        run: |
-          source $(conda info --base)/etc/profile.d/conda.sh
           conda activate test_env || { echo "Failed to activate conda env"; exit 1; }
+
+      - name: Install dependencies
+        run: |
           which python
           conda install -c conda-forge gxx=11 gcc=11
-          
+          conda activate test_env || { echo "Failed to activate conda env"; exit 1; }
+          echo "Installing dependencies"
+          pip install 
+      
+    
+
+  clean-up:
+    runs-on: self-hosted
+    needs: set-up-test-env
+
+    steps:
+      - name: Clean up
+        run: |
+          echo $PWD
